services:
  - type: web
    name: la-victoire-house
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm run build && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: victoirehouse-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: FRONTEND_URL
        value: https://la-victoire-house.onrender.com

databases:
  - name: victoirehouse-db
    region: frankfurt
    plan: free
    ipAllowList: []
